"""empty message

Revision ID: 1683ebfc4950
Revises: 
Create Date: 2022-01-24 21:58:57.823930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1683ebfc4950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='companies')
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False))
    op.create_index('name', 'companies', ['name'], unique=False)
    # ### end Alembic commands ###
