"""empty message

Revision ID: 68c7283675c0
Revises: 1683ebfc4950
Create Date: 2022-01-26 22:06:05.775610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c7283675c0'
down_revision = '1683ebfc4950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='company_names')
    op.drop_index('name', table_name='tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'tags', ['name'], unique=False)
    op.create_index('name', 'company_names', ['name'], unique=False)
    # ### end Alembic commands ###
