"""empty message

Revision ID: f7fa4640f5fc
Revises: 722c3abdcbfe
Create Date: 2022-01-26 23:16:47.041418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fa4640f5fc'
down_revision = '722c3abdcbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('lang', table_name='company_names')
    op.drop_index('name', table_name='company_names')
    op.drop_index('lang', table_name='tags')
    op.drop_index('name', table_name='tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'tags', ['name'], unique=False)
    op.create_index('lang', 'tags', ['lang'], unique=False)
    op.create_index('name', 'company_names', ['name'], unique=False)
    op.create_index('lang', 'company_names', ['lang'], unique=False)
    # ### end Alembic commands ###
